

# 01: Numeric Literals

a = 0b1010 #Binary Literals
b = 100 # Decimal Literls
c = 0o310 # That is Octal literal
d = 0x12c #Hexadecimal Literal

#Float Literal
float_1 = 10.5
float_2 = 1.5e2


#complex Literal
x = 3.14j


print(a, b, c, d)
print(float_1, float_2)
print(x, x.imag, x.real)


# 032: String Literals


strings = "Coffee Tag"
char = "C"
multiline_str = "This is a multiple string with more than one line code."
unicode = u"\u00dcnic\u00f6de"
raw_str = r"\n raw \n string"


print(strings)
print(char)
print(multiline_str)
print(unicode)
print(raw_str)



# 03: Booleam Literals

x = (1 == True)
y = (1 == False)
a = True + 4
b = False + 10

print("x is", x)
print("y is", y)
print("a: ",a)
print("b: ",b)









